# Generated by Django 5.0.6 on 2024-05-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('account', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('note', models.CharField(max_length=300)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
    ]
